### PR TITLE
Fix Windows build breaks

### LINKED ISSUE #61: Upstream MLIR change introduced a Windows build break
An upstream [MLIR change](https://github.com/llvm/llvm-project/commit/6569cf2a44bf95106e7168bdb79c4674742708fa) introduced a dependency on `llvm::ThreadPool`. The problem is that this thread pool is currently [disabled on Windows to workaround an LLVM bug](https://github.com/tensorflow/runtime/blob/master/third_party/llvm/llvm.bzl#L298-L301).

```
ERROR: external/llvm-project/mlir/BUILD:5066:10: Linking external/llvm-project/mlir/mlir-linalg-ods-yaml-gen.exe [for host] failed: (Exit 1120): link.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64/link.exe @bazel-out/host/bin/external/llvm-project/mlir/mlir-linalg-ods-yaml-gen.exe-2.params
IR.lib(Verifier.obj) : error LNK2019: unresolved external symbol "public: bool __cdecl llvm::ThreadPool::isWorkerThread(void)const " (?isWorkerThread@ThreadPool@llvm@@QEBA_NXZ) referenced in function "struct mlir::LogicalResult __cdecl mlir::failableParallelForEach<class mlir::Operation * *,class <lambda_1e2c9a1d5fe91ce52e6f54677d3c54a3> >(class mlir::MLIRContext *,class mlir::Operation * *,class mlir::Operation * *,class <lambda_1e2c9a1d5fe91ce52e6f54677d3c54a3> 
&&)" (??$failableParallelForEach@PEAPEAVOperation@mlir@@V<lambda_1e2c9a1d5fe91ce52e6f54677d3c54a3>@@@mlir@@YA?AULogicalResult@0@PEAVMLIRContext@0@PEAPEAVOperation@0@1$$QEAV<lambda_1e2c9a1d5fe91ce52e6f54677d3c54a3>@@@Z)
bazel-out\host\bin\external\llvm-project\mlir\mlir-linalg-ods-yaml-gen.exe : fatal error LNK1120: 1 unresolved externals
Target //tools:bef_executor failed to build
```

### PR DESCRIPTION
**Pull request by tlemo**
This PR fixes #61 and #67

#61 - Don't disable LLVM_ENABLE_THREADS. The root LLVM issue appears to be fixed (https://bugs.llvm.org/show_bug.cgi?id=44211) and recent MLIR changes introduced a dependency on llvm::ThreadPool

#67 - MSVC requires consistent struct/class usage across declarations and definitions. This is technically a MSVC bug, but with a long history and unlikely to get fixed (the struct/class result in different name name mangling and will result in painful to debug linking issues)

### CODE REVIEW

File: include/tfrt/host_context/diagnostic.h [hunk 1]
```diff
@@ -33,7 +33,8 @@ namespace tfrt {
 class ExecutionContext;
 
 // This is a simple representation of a decoded diagnostic.
-struct DecodedDiagnostic {
+class DecodedDiagnostic {
```
Comment (chsigg) [inline include/tfrt/host_context/diagnostic.h:36]: I would rather change the forward declarations to struct, because our internal linter will barf at class member naming.

**Review by chsigg — COMMENTED** [review]
Thanks Leonard!

I did find https://stackoverflow.com/a/52366333 in the meantime and the struct > class change now makes sense.

I will merge this change manually...

File: include/tfrt/host_context/diagnostic.h (hunk 1 above)
Comment (tlemo) [reply include/tfrt/host_context/diagnostic.h:36]: sounds good to me!
